name: First Demo Action

on:
  push:
    branches:
      - main

jobs:
  demo-jobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actions Started"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello, World!"
      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script"
          echo "It is running on the runner in the cloud"
      - name: List files in the repository
        run: ls ${{ github.workspace }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo "$GITHUB_CONTEXT"
      - name: Action Completed
        run: echo "Actions Completed"
